# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

project 'RamlExample.xcodeproj'

platform :ios, "8.0"

target :'RamlExample' do
    pod 'RamlSDK', :path => '../'	
end
